const daysArray = [
    [
        //0
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''},
        { name: '', imageLink: ''}

    ],
    [
        //1
    ],
    [
        //2
    ],
    [
        //3
    ],
    [
        //4
    ],
    [
        //5
    ],
    [
        { day: 1, name: 'День сала', month:'july', imageLink: '/july/1'},
        { day: 2, name: 'День туберкулезного варенья', month:'july', imageLink: '/july/2'},
        { day: 3, name: 'День солёного пловчика', month:'july', imageLink: '/july/3'},
        { day: 4, name: 'День вкусного и маринованного фери', month:'july', imageLink: '/july/4'},
        { day: 5, name: 'День глазированного сырка', month:'july', imageLink: '/july/5'},
        { day: 6, name: 'День компьюетрной памяти', month:'july', imageLink: '/july/6'},
        { day: 7, name: 'День овсянки', month:'july', imageLink: '/july/7'},
        { day: 8, name: 'День хрустящего и топленого бетона', month:'july', imageLink: '/july/8'},
        { day: 9, name: 'День дошика', month:'july', imageLink: '/july/9'},
        { day: 10, name: 'День рентв', month:'july', imageLink: '/july/10'},
        { day: 11, name: 'День мухобойки', month:'july', imageLink: '/july/11'},
        { day: 12, name: 'День Паши Техника', month:'july', imageLink: '/july/12'},
        { day: 13, name: 'День бабушкиного компота', month:'july', imageLink: '/july/13'},
        { day: 14, name: 'День спорта', month:'july', imageLink: '/july/14'},
        { day: 15, name: 'День хип-хопа', month:'july', imageLink: '/july/15'},
        { day: 16, name: 'День ненахода', month:'july', imageLink: '/july/16'},
        { day: 17, name: 'День маслянистых помидоров', month:'july', imageLink: '/july/17'},
        { day: 18, name: 'День выгу выгу выгу', month:'july', imageLink: '/july/18'},
        { day: 19, name: 'День сранья в кувшин', month:'july', imageLink: '/july/19'},
        { day: 20, name: 'День джэка дэниалс', month:'july', imageLink: '/july/20'},
        { day: 21, name: 'День дауна', month:'july', imageLink: '/july/21'},
        { day: 22, name: 'День гнилой плоти', month:'july', imageLink: '/july/22'},
        { day: 23, name: 'День кисленького техно', month:'july', imageLink: '/july/23'},
        { day: 24, name: 'День блока кузовной электроники', month:'july', imageLink: '/july/24'},
        { day: 25, name: 'День пакета', month:'july', imageLink: '/july/25'},
        { day: 26, name: 'День беды с башкой', month:'july', imageLink: '/july/26'},
        { day: 27, name: 'День месчных', month:'july', imageLink: '/july/27'},
        { day: 28, name: 'День забора атестатов', month:'july', imageLink: '/july/28'},
        { day: 29, name: 'День томатного сока', month:'july', imageLink: '/july/29'},
        { day: 30, name: 'День втулок', month:'july', imageLink: '/july/30'},
        { day: 31, name: 'День арбуза', month:'july', imageLink: '/july/31'}
    ],  //6
    [
        { day: 1, name: '', month:'august', imageLink: '/august/1'},
        { day: 2, name: '', month:'august', imageLink: '/august/2'},
        { day: 3, name: '', month:'august', imageLink: '/august/3'},
        { day: 4, name: '', month:'august', imageLink: '/august/4'},
        { day: 5, name: '', month:'august', imageLink: '/august/5'},
        { day: 6, name: '', month:'august', imageLink: '/august/6'},
        { day: 7, name: '', month:'august', imageLink: '/august/7'},
        { day: 8, name: '', month:'august', imageLink: '/august/8'},
        { day: 9, name: '', month:'august', imageLink: '/august/9'},
        { day: 10, name: '', month:'august', imageLink: '/august/10'},
        { day: 11, name: '', month:'august', imageLink: '/august/11'},
        { day: 12, name: '', month:'august', imageLink: '/august/12'},
        { day: 13, name: '', month:'august', imageLink: '/august/13'},
        { day: 14, name: '', month:'august', imageLink: '/august/14'},
        { day: 15, name: '', month:'august', imageLink: '/august/15'},
        { day: 16, name: '', month:'august', imageLink: '/august/16'},
        { day: 17, name: '', month:'august', imageLink: '/august/17'},
        { day: 18, name: '', month:'august', imageLink: '/august/18'},
        { day: 19, name: '', month:'august', imageLink: '/august/19'},
        { day: 20, name: '', month:'august', imageLink: '/august/20'},
        { day: 21, name: '', month:'august', imageLink: '/august/21'},
        { day: 22, name: '', month:'august', imageLink: '/august/22'},
        { day: 23, name: '', month:'august', imageLink: '/august/23'},
        { day: 24, name: '', month:'august', imageLink: '/august/24'},
        { day: 25, name: '', month:'august', imageLink: '/august/25'},
        { day: 26, name: '', month:'august', imageLink: '/august/26'},
        { day: 27, name: '', month:'august', imageLink: '/august/27'},
        { day: 28, name: '', month:'august', imageLink: '/august/28'},
        { day: 29, name: '', month:'august', imageLink: '/august/29'},
        { day: 30, name: '', month:'august', imageLink: '/august/30'},
        { day: 31, name: '', month:'august', imageLink: '/august/31'}
    ], //7
    [
        { day: 1, name: '', month:'september', imageLink: '/september/1'},
        { day: 2, name: '', month:'september', imageLink: '/september/2'},
        { day: 3, name: '', month:'september', imageLink: '/september/3'},
        { day: 4, name: '', month:'september', imageLink: '/september/4'},
        { day: 5, name: '', month:'september', imageLink: '/september/5'},
        { day: 6, name: '', month:'september', imageLink: '/september/6'},
        { day: 7, name: '', month:'september', imageLink: '/september/7'},
        { day: 8, name: '', month:'september', imageLink: '/september/8'},
        { day: 9, name: '', month:'september', imageLink: '/september/9'},
        { day: 10, name: '', month:'september', imageLink: '/september/10'},
        { day: 11, name: '', month:'september', imageLink: '/september/11'},
        { day: 12, name: '', month:'september', imageLink: '/september/12'},
        { day: 13, name: '', month:'september', imageLink: '/september/13'},
        { day: 14, name: '', month:'september', imageLink: '/september/14'},
        { day: 15, name: '', month:'september', imageLink: '/september/15'},
        { day: 16, name: '', month:'september', imageLink: '/september/16'},
        { day: 17, name: '', month:'september', imageLink: '/september/17'},
        { day: 18, name: '', month:'september', imageLink: '/september/18'},
        { day: 19, name: '', month:'september', imageLink: '/september/19'},
        { day: 20, name: '', month:'september', imageLink: '/september/20'},
        { day: 21, name: '', month:'september', imageLink: '/september/21'},
        { day: 22, name: '', month:'september', imageLink: '/september/22'},
        { day: 23, name: '', month:'september', imageLink: '/september/23'},
        { day: 24, name: '', month:'september', imageLink: '/september/24'},
        { day: 25, name: '', month:'september', imageLink: '/september/25'},
        { day: 26, name: '', month:'september', imageLink: '/september/26'},
        { day: 27, name: '', month:'september', imageLink: '/september/27'},
        { day: 28, name: '', month:'september', imageLink: '/september/28'},
        { day: 29, name: '', month:'september', imageLink: '/september/29'},
        { day: 30, name: '', month:'september', imageLink: '/september/30'},
    ], //8
    [
        { day: 1, name: '', month:'october', imageLink: '/october/1'},
        { day: 2, name: '', month:'october', imageLink: '/october/2'},
        { day: 3, name: '', month:'october', imageLink: '/october/3'},
        { day: 4, name: '', month:'october', imageLink: '/october/4'},
        { day: 5, name: '', month:'october', imageLink: '/october/5'},
        { day: 6, name: '', month:'october', imageLink: '/october/6'},
        { day: 7, name: '', month:'october', imageLink: '/october/7'},
        { day: 8, name: '', month:'october', imageLink: '/october/8'},
        { day: 9, name: '', month:'october', imageLink: '/october/9'},
        { day: 10, name: '', month:'october', imageLink: '/october/10'},
        { day: 11, name: '', month:'october', imageLink: '/october/11'},
        { day: 12, name: '', month:'october', imageLink: '/october/12'},
        { day: 13, name: '', month:'october', imageLink: '/october/13'},
        { day: 14, name: '', month:'october', imageLink: '/october/14'},
        { day: 15, name: '', month:'october', imageLink: '/october/15'},
        { day: 16, name: '', month:'october', imageLink: '/october/16'},
        { day: 17, name: '', month:'october', imageLink: '/october/17'},
        { day: 18, name: '', month:'october', imageLink: '/october/18'},
        { day: 19, name: '', month:'october', imageLink: '/october/19'},
        { day: 20, name: '', month:'october', imageLink: '/october/20'},
        { day: 21, name: '', month:'october', imageLink: '/october/21'},
        { day: 22, name: '', month:'october', imageLink: '/october/22'},
        { day: 23, name: '', month:'october', imageLink: '/october/23'},
        { day: 24, name: '', month:'october', imageLink: '/october/24'},
        { day: 25, name: '', month:'october', imageLink: '/october/25'},
        { day: 26, name: '', month:'october', imageLink: '/october/26'},
        { day: 27, name: '', month:'october', imageLink: '/october/27'},
        { day: 28, name: '', month:'october', imageLink: '/october/28'},
        { day: 29, name: '', month:'october', imageLink: '/october/29'},
        { day: 30, name: '', month:'october', imageLink: '/october/30'},
        { day: 31, name: '', month:'october', imageLink: '/october/31'}
    ], //9
    [
        { day: 1, name: '', month:'november', imageLink: '/november/1'},
        { day: 2, name: '', month:'november', imageLink: '/november/2'},
        { day: 3, name: '', month:'november', imageLink: '/november/3'},
        { day: 4, name: '', month:'november', imageLink: '/november/4'},
        { day: 5, name: '', month:'november', imageLink: '/november/5'},
        { day: 6, name: '', month:'november', imageLink: '/november/6'},
        { day: 7, name: '', month:'november', imageLink: '/november/7'},
        { day: 8, name: '', month:'november', imageLink: '/november/8'},
        { day: 9, name: '', month:'november', imageLink: '/november/9'},
        { day: 10, name: '', month:'november', imageLink: '/november/10'},
        { day: 11, name: '', month:'november', imageLink: '/november/11'},
        { day: 12, name: '', month:'november', imageLink: '/november/12'},
        { day: 13, name: '', month:'november', imageLink: '/november/13'},
        { day: 14, name: '', month:'november', imageLink: '/november/14'},
        { day: 15, name: '', month:'november', imageLink: '/november/15'},
        { day: 16, name: '', month:'november', imageLink: '/november/16'},
        { day: 17, name: '', month:'november', imageLink: '/november/17'},
        { day: 18, name: '', month:'november', imageLink: '/november/18'},
        { day: 19, name: '', month:'november', imageLink: '/november/19'},
        { day: 20, name: '', month:'november', imageLink: '/november/20'},
        { day: 21, name: '', month:'november', imageLink: '/november/21'},
        { day: 22, name: '', month:'november', imageLink: '/november/22'},
        { day: 23, name: '', month:'november', imageLink: '/november/23'},
        { day: 24, name: '', month:'november', imageLink: '/november/24'},
        { day: 25, name: '', month:'november', imageLink: '/november/25'},
        { day: 26, name: '', month:'november', imageLink: '/november/26'},
        { day: 27, name: '', month:'november', imageLink: '/november/27'},
        { day: 28, name: '', month:'november', imageLink: '/november/28'},
        { day: 29, name: '', month:'november', imageLink: '/november/29'},
        { day: 30, name: '', month:'november', imageLink: '/november/30'}
    ], //10
    [
        { day: 1, name: '', month:'december', imageLink: '/december/1'},
        { day: 2, name: '', month:'december', imageLink: '/december/2'},
        { day: 3, name: '', month:'december', imageLink: '/december/3'},
        { day: 4, name: '', month:'december', imageLink: '/december/4'},
        { day: 5, name: '', month:'december', imageLink: '/december/5'},
        { day: 6, name: '', month:'december', imageLink: '/december/6'},
        { day: 7, name: '', month:'december', imageLink: '/december/7'},
        { day: 8, name: '', month:'december', imageLink: '/december/8'},
        { day: 9, name: '', month:'december', imageLink: '/december/9'},
        { day: 10, name: '', month:'december', imageLink: '/december/10'},
        { day: 11, name: '', month:'december', imageLink: '/december/11'},
        { day: 12, name: '', month:'december', imageLink: '/december/12'},
        { day: 13, name: '', month:'december', imageLink: '/december/13'},
        { day: 14, name: '', month:'december', imageLink: '/december/14'},
        { day: 15, name: '', month:'december', imageLink: '/december/15'},
        { day: 16, name: '', month:'december', imageLink: '/december/16'},
        { day: 17, name: '', month:'december', imageLink: '/december/17'},
        { day: 18, name: '', month:'december', imageLink: '/december/18'},
        { day: 19, name: '', month:'december', imageLink: '/december/19'},
        { day: 20, name: '', month:'december', imageLink: '/december/20'},
        { day: 21, name: '', month:'december', imageLink: '/december/21'},
        { day: 22, name: '', month:'december', imageLink: '/december/22'},
        { day: 23, name: '', month:'december', imageLink: '/december/23'},
        { day: 24, name: '', month:'december', imageLink: '/december/24'},
        { day: 25, name: '', month:'december', imageLink: '/december/25'},
        { day: 26, name: '', month:'december', imageLink: '/december/26'},
        { day: 27, name: '', month:'december', imageLink: '/december/27'},
        { day: 28, name: '', month:'december', imageLink: '/december/28'},
        { day: 29, name: '', month:'december', imageLink: '/december/29'},
        { day: 30, name: '', month:'december', imageLink: '/december/30'},
        { day: 31, name: '', month:'december', imageLink: '/december/31'}
    ] //11
];

module.exports = daysArray;